sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
# before tests
before_script:
  - pip3 install flake8
  - pip3 install pylint
  - pip3 install coverage
  - pip3 install nose-testconfig
  - flake8 bluew
  - pylint bluew
# command to run tests
script:
  - nosetests -a '!req_engine'
