sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip list  # Do noting for now
# before tests
before_script:
  - pip3 install flake8
  - pip3 install pylint
  - pip3 install mypy==0.560
  - pip3 install nose-testconfig
  - flake8 bluew --ignore=F401
  - mypy --no-warn-no-return --ignore-missing-imports .
# command to run tests
script:
  - pylint --rcfile=.pylintrc --notes=FIXME bluew
